using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cirrus.SourceGenerators;

[Generator]
public class DuckTypingGenerator : IIncrementalGenerator
{
    private const string DuckTypingAttributesSource = """
// <auto-generated/>

using System;

namespace Cirrus.Generated.Attributes;

/// <summary>
/// Attribute to mark a method as a duck property getter.
/// The method should have exactly two parameters: the target object and the specified property value of the object (out value).
/// The named of the duck property is specified by the constructor parameter <paramref name="propertyName"/>.
/// And the type of the duck property is determined by the type of the second parameter of the method.
/// The source generator will search all types in the specified assemblies (or all assemblies if not specified)
/// that contains the duck property and implement the method.
/// The method should return a <see cref="bool"/> value,
/// indicating whether the object is matched with one of the types found in the assemblies.
/// </summary>
/// <param name="propertyName">Name of the duck property.</param>
[AttributeUsage(AttributeTargets.Method)]
internal class DuckPropertyGetterAttribute(string propertyName) : Attribute
{
    /// <summary>
    /// Name of the duck property. This is used to identify the duck property from all possible object types.
    /// </summary>
    public string PropertyName { get; } = propertyName;
    
    /// <summary>
    /// Optional list of assembly names to limit the search scope of duck property getters.
    /// If this is not set, all assemblies will be searched.
    /// </summary>
    public string[] Assemblies { get; init; } = [];
}

/// <summary>
/// Attribute to mark a method as a duck property setter.
/// The method should have exactly two parameters: the target object and the specified property value of the object.
/// The named of the duck property is specified by the constructor parameter <paramref name="propertyName"/>.
/// And the type of the duck property is determined by the type of the second parameter of the method.
/// The source generator will search all types in the specified assemblies (or all assemblies if not specified)
/// that contains the duck property and implement the method.
/// The method should return a <see cref="bool"/> value,
/// indicating whether the object is matched with one of the types found in the assemblies.
/// </summary>
/// <param name="propertyName">Name of the duck property.</param>
[AttributeUsage(AttributeTargets.Method)]
internal class DuckPropertySetterAttribute(string propertyName) : Attribute
{
    /// <summary>
    /// Name of the duck property. This is used to identify the duck property from all possible object types.
    /// </summary>
    public string PropertyName { get; } = propertyName;
    
    /// <summary>
    /// Optional list of assembly names to limit the search scope of duck property getters.
    /// If this is not set, all assemblies will be searched.
    /// </summary>
    public string[] Assemblies { get; init; } = [];
}

/// <summary>
/// Attribute to mark a method as a duck method.
/// The method should have at least one parameter: the target object.
/// Next comes the parameter list for the duck method. If the method has a return value,
/// it should be set as the last "out" parameter.
/// The named of the duck method is specified by the constructor parameter <paramref name="methodName"/>.
/// The source generator will search all types in the specified assemblies (or all assemblies if not specified)
/// that contains the duck method and implement the attributed method.
/// The method should return a <see cref="bool"/> value,
/// indicating whether the object is matched with one of the types found in the assemblies.
/// </summary>
/// <param name="methodName">Name of the duck method.</param>
[AttributeUsage(AttributeTargets.Method)]
internal class DuckMethodAttribute(string methodName) : Attribute
{
    /// <summary>
    /// Name of the duck property. This is used to identify the duck property from all possible object types.
    /// </summary>
    public string MethodName { get; } = methodName;
    
    /// <summary>
    /// Optional list of assembly names to limit the search scope of duck property getters.
    /// If this is not set, all assemblies will be searched.
    /// </summary>
    public string[] Assemblies { get; init; } = [];
}
""";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("DuckingTypeAttributes.g.cs", SourceText.From(DuckTypingAttributesSource, Encoding.UTF8));
        });

        var methodDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is MethodDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    var methodSyntax = (MethodDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(methodSyntax) is not { } symbol) return null;
                    var hasDuckAttr = symbol.GetAttributes().Any(a =>
                        a.AttributeClass?.Name is
                            "DuckPropertyGetterAttribute" or
                            "DuckPropertySetterAttribute" or
                            "DuckMethodAttribute"
                    );
                    return hasDuckAttr ? symbol : null;
                }
            ).Where(static m => m is not null);
        
        var compilationAndMethods = context.CompilationProvider.Combine(methodDeclarations.Collect());
        
        context.RegisterSourceOutput(compilationAndMethods, static (spc, source) =>
        {
            var compilation = source.Left;
            var methods = source.Right;

            if (methods.IsDefaultOrEmpty) return;

            var groupClasses = methods.Cast<IMethodSymbol>()
                .GroupBy(m => m.ContainingType, SymbolEqualityComparer.Default);

            foreach (var classGroup in groupClasses)
            {
                var containingClass = (INamedTypeSymbol)classGroup.Key!;
                var namespaceName = containingClass.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : containingClass.ContainingNamespace.ToDisplayString();
                var className = containingClass.Name;

                StringBuilder sb = new();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine();
                sb.AppendLine("using System;");
                sb.AppendLine();

                if (namespaceName is not null)
                {
                    sb.AppendLine($"namespace {namespaceName};");
                    sb.AppendLine();
                }

                var accessibility = containingClass.DeclaredAccessibility switch {
                    Accessibility.Public => "public ",
                    _ => "internal "
                };
                var classModifiers = containingClass.IsStatic ? $"{accessibility}static partial" : $"{accessibility}partial";
                
                sb.AppendLine($"{classModifiers} class {className}");
                sb.AppendLine("{");
                sb.AppendLine();

                foreach (var method in classGroup)
                {
                    GenerateMethodBody(sb, method, compilation, "    ");
                }
                
                sb.AppendLine("}");
                
                spc.AddSource($"{className}_DuckTyping.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        });
    }

    private static void GenerateMethodBody(StringBuilder sb, IMethodSymbol method, Compilation compilation,
        string indent)
    {
        if (method.Parameters.Length == 0 ||
            method.ReturnType.SpecialType != SpecialType.System_Boolean) return;
        
        var attr = method.GetAttributes().First(a =>
            a.AttributeClass?.Name is
                "DuckPropertyGetterAttribute" or
                "DuckPropertySetterAttribute" or
                "DuckMethodAttribute"
        );
        var attrName = attr.AttributeClass!.Name;
        var isProperty = attrName != "DuckMethodAttribute";
        
        var isSetter = attrName == "DuckPropertySetterAttribute";
        var baseTypeSymbol = method.Parameters[0].Type;
        var targetMemberName = (string)attr.ConstructorArguments[0].Value!;
        
        var assemblies = GatherAssemblies(attr);
        var matchedTypes = GetMatchedTypes(compilation, method, baseTypeSymbol, targetMemberName, attrName, assemblies);

        var accessibility = method.DeclaredAccessibility switch
        {
            Accessibility.Public => "public ",
            Accessibility.Internal => "internal ",
            Accessibility.Protected => "protected ",
            Accessibility.Private => "private ",
            _ => string.Empty
        };
        var staticModifier = method.IsStatic ? "static " : string.Empty;
        string modifiers = $"{accessibility}{staticModifier}partial";

        var paramList = new List<string>();
        foreach (var p in method.Parameters)
        {
            string refKind = p.RefKind switch
            {
                RefKind.Out => "out ",
                RefKind.Ref => "ref ",
                RefKind.In => "in ",
                _ => string.Empty
            };
            paramList.Add($"{refKind}{p.Type.ToDisplayString()} {p.Name}");
        }
        string parameters = string.Join(", ", paramList);

        sb.AppendLine($"{indent}{modifiers} bool {method.Name}({parameters})");
        sb.AppendLine($"{indent}{{");

        var argsParamName = method.Parameters[0].Name;

        if (isProperty)
        {
            if (isSetter)
            {
                if (method.Parameters.Length != 2) return;
                var valueParamName = method.Parameters[1].Name;
                sb.AppendLine($"{indent}    switch ({argsParamName})");
                sb.AppendLine($"{indent}    {{");
                foreach (var type in matchedTypes)
                {
                    sb.AppendLine(
                        $"{indent}        case {type.ToDisplayString()} _obj_: _obj_.{targetMemberName} = {valueParamName}; return true;");
                }
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    return false;");
            }
            else
            {
                if (method.Parameters.Length != 2) return;
                var outParamName = method.Parameters[1].Name;
                sb.AppendLine($"{indent}    switch ({argsParamName})");
                sb.AppendLine($"{indent}    {{");
                foreach (var type in matchedTypes)
                {
                    sb.AppendLine(
                        $"{indent}        case {type.ToDisplayString()} _obj_: {outParamName} = _obj_.{targetMemberName}; return true;");
                }
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    {outParamName} = default!;");
                sb.AppendLine($"{indent}    return false;");
            }
        }
        else
        {
            var lastParam = method.Parameters.Last();
            bool hasOutReturn = lastParam.RefKind == RefKind.Out;
            if (hasOutReturn)
            {
                var outParamName = lastParam.Name;
                var invokeArgs = string.Join(", ",
                    method.Parameters.Skip(1).Take(method.Parameters.Length - 2).Select(p => p.Name));
                sb.AppendLine($"{indent}    switch ({argsParamName})");
                sb.AppendLine($"{indent}    {{");
                foreach (var type in matchedTypes)
                {
                    sb.AppendLine(
                        $"{indent}        case {type.ToDisplayString()} _obj_: {outParamName} = _obj_.{targetMemberName}({invokeArgs}); return true;");
                }
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    {outParamName} = default!;");
                sb.AppendLine($"{indent}    return false;");
            }
            else
            {
                var invokeArgs = string.Join(", ", method.Parameters.Skip(1).Select(p => p.Name));
                sb.AppendLine($"{indent}    switch ({argsParamName})");
                sb.AppendLine($"{indent}    {{");
                foreach (var type in matchedTypes)
                {
                    sb.AppendLine(
                        $"{indent}        case {type.ToDisplayString()} _obj_: _obj_.{targetMemberName}({invokeArgs}); return true;");
                }
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}    return false;");
            }
        }
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }
    
    private static HashSet<string> GatherAssemblies(AttributeData attr)
    {
        HashSet<string> assemblies = [];
        var assembliesArgs = attr.NamedArguments.FirstOrDefault(kv => kv.Key == "Assemblies").Value;
        if (!assembliesArgs.IsNull)
        {
            foreach (var v in assembliesArgs.Values)
            {
                if (v.Value is string s) assemblies.Add(s);
            }
        }
        return assemblies;
    }

    private static List<INamedTypeSymbol> GetMatchedTypes(
        Compilation compilation,
        IMethodSymbol originalMethod,
        ITypeSymbol baseTypeSymbol,
        string targetMemberName,
        string attrName,
        HashSet<string> assemblies)
    {
        List<INamedTypeSymbol> matchedTypes = [];
        HashSet<IAssemblySymbol> assembliesToScan = new(SymbolEqualityComparer.Default)
        {
            compilation.Assembly
        };
        bool hasExplicitScope = assemblies.Count > 0;
        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol asmSymbol)
            {
                if (hasExplicitScope)
                {
                    if (assemblies.Contains(asmSymbol.Name)) assembliesToScan.Add(asmSymbol);
                }
                else if (baseTypeSymbol.SpecialType != SpecialType.System_Object)
                {
                    assembliesToScan.Add(asmSymbol);
                }
            }
        }

        bool isProperty = attrName != "DuckMethodAttribute";
        bool isSetter = attrName == "DuckPropertySetterAttribute";
        bool hasOutReturn = !isProperty && originalMethod.Parameters.Length > 0 &&
                            originalMethod.Parameters.Last().RefKind == RefKind.Out;

        ITypeSymbol? expectedPropType = null;
        if (isProperty && originalMethod.Parameters.Length == 2)
        {
            expectedPropType = originalMethod.Parameters[1].Type;
        }

        List<ITypeSymbol>? expectedMethodArgs = null;
        ITypeSymbol? expectedReturnType = null;
        if (!isProperty)
        {
            if (hasOutReturn)
            {
                expectedMethodArgs = originalMethod.Parameters.Skip(1).Take(originalMethod.Parameters.Length - 2).Select(p => p.Type).ToList();
                expectedReturnType = originalMethod.Parameters.Last().Type;
            }
            else
            {
                expectedMethodArgs = originalMethod.Parameters.Skip(1).Select(p => p.Type).ToList();
            }
        }
        
        void ScanNamespace(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                if (type.IsAbstract) continue;
                if (!InheritsFrom(type, baseTypeSymbol)) continue;

                bool hasMember = type.GetMembers(targetMemberName).Any(m =>
                {
                    if (isProperty)
                    {
                        if (m is IPropertySymbol prop)
                        {
                            if (isSetter && prop.SetMethod is null) return false;
                            if (!isSetter && prop.GetMethod is null) return false;
                            if (expectedPropType is not null)
                            {
                                return isSetter
                                    ? compilation.ClassifyConversion(expectedPropType, prop.Type).IsImplicit
                                    : compilation.ClassifyConversion(prop.Type, expectedPropType).IsImplicit;
                            }
                            return true;
                        }
                    }
                    else
                    {
                        if (m is IMethodSymbol methodSym)
                        {
                            if (methodSym.Parameters.Length != expectedMethodArgs!.Count) return false;

                            for (var i = 0; i < methodSym.Parameters.Length; i++)
                            {
                                if (!compilation.ClassifyConversion(expectedMethodArgs[i], methodSym.Parameters[i].Type).IsImplicit)
                                    return false;
                            }

                            if (hasOutReturn)
                            {
                                if (methodSym.ReturnsVoid) return false;
                                if (!compilation.ClassifyConversion(methodSym.ReturnType, expectedReturnType!).IsImplicit)
                                    return false;
                            }
                            
                            return true;
                        }
                    }

                    return false;
                });

                if (hasMember)
                {
                    matchedTypes.Add(type);
                }
            }

            foreach (var childNs in ns.GetNamespaceMembers())
            {
                ScanNamespace(childNs);
            }
        }
        
        foreach (var asm in assembliesToScan)
        {
            ScanNamespace(asm.GlobalNamespace);
        }
        
        return matchedTypes;
    }

    private static bool InheritsFrom(ITypeSymbol type, ITypeSymbol baseType)
    {
        if (baseType.SpecialType == SpecialType.System_Object) return true;
        if (SymbolEqualityComparer.Default.Equals(type, baseType)) return true;
        var currentBaseType = type.BaseType;
        while (currentBaseType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(currentBaseType, baseType)) return true;
            currentBaseType = currentBaseType.BaseType;
        }
        if (baseType.TypeKind == TypeKind.Interface)
        {
            return type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, baseType));
        }
        return false;
    }
}