using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cirrus.SourceGenerators;

[Generator]
public class MusicApiGenerator : IIncrementalGenerator
{
    private const string MusicApiAttributesSource = """
// <auto-generated/>

using System;

namespace Cirrus.Generated.Attributes;

/// <summary>
/// Attribute to mark API containers in the client.
/// </summary>
/// <param name="containerName">Name of the container, used for routing the APIs.</param>
[AttributeUsage(AttributeTargets.Property)]
internal class MusicApiContainerAttribute(string containerName) : Attribute
{
    /// <summary>
    /// Gets the name of the API container.
    /// </summary>
    public string ContainerName => containerName;
}

/// <summary>
/// Attribute to mark API definitions.
/// </summary>
/// <param name="apiName">Name of the API, used for routing.</param>
[AttributeUsage(AttributeTargets.Property)]
internal class MusicApiAttribute(string apiName) : Attribute
{
    /// <summary>
    /// Gets the name of the API.
    /// </summary>
    public string ApiName => apiName;
}
""";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("MusicApiAttributes.g.cs", SourceText.From(MusicApiAttributesSource, Encoding.UTF8));
        });

        var containers = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Cirrus.Generated.Attributes.MusicApiContainerAttribute",
            static (node, _) => node is PropertyDeclarationSyntax,
            static (context, _) =>
            {
                var property = context.TargetSymbol as IPropertySymbol;
                var data = context.Attributes[0];
                var containerRoute = data.ConstructorArguments[0].Value as string;
                return new ContainerMeta(containerRoute!, property!.Name, (property.Type as INamedTypeSymbol)!);
            });

        var containersWithApis = containers.Select((cm, _) =>
        {
            var apis = cm.ContainerType.GetMembers()
                .OfType<IPropertySymbol>()
                .Select(static p => (
                    Property: p,
                    Attribute: p.GetAttributes().FirstOrDefault(a =>
                        a.AttributeClass?.ToDisplayString() is "Cirrus.Generated.Attributes.MusicApiAttribute")
                ))
                .Where(static p => p is not {Attribute: null})
                .Select(static p => new ApiMeta(
                    (p.Attribute!.ConstructorArguments[0].Value as string)!,
                    p.Property.Name
                ))
                .ToArray();
            return new ContainerMetaWithApis(cm, apis);
        });
        
        context.RegisterSourceOutput(containersWithApis.Collect(), static (spc, apis) =>
        {
            if (!apis.SelectMany(c => c.Apis).Any()) return;
            StringBuilder sb = new();
            sb.AppendLine("""
                          // <auto-generated/>
                          
                          #nullable enable

                          using Cirrus.Network.Primitives;
                          
                          namespace Cirrus.Network;

                          partial class Client
                          {
                              /// <summary>
                                  /// Gets an API from the singleton instance of the client.
                              /// </summary>
                              /// <param name="containerName">Name of the API container.</param>
                              /// <param name="apiName">Name of the API.</param>
                              /// <returns>The API object; null if not found.</returns>
                              internal static IMusicApi? GetApiFromPath(string containerName, string apiName)
                              {
                                  return (containerName, apiName) switch
                                  {
                          """);
            foreach (var container in apis)
            {
                foreach (var api in container.Apis)
                {
                    sb.AppendLine($"            (\"{container.Container.Route}\", \"{api.Route}\") => {container.Container.Accessor}.{api.Accessor},");
                }
            }
            sb.AppendLine("""
                                      _ => null
                                  };
                              }
                          }
                          """);
            spc.AddSource("Cirrus.Network.Client.MusicApiLookup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private record struct ContainerMeta(string Route, string Accessor, INamedTypeSymbol ContainerType);
    private record struct ApiMeta(string Route, string Accessor);
    private record struct ContainerMetaWithApis(ContainerMeta Container, ApiMeta[] Apis);
}