using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cirrus.SourceGenerators;

[Generator]
public class NamedEventTriggerBehaviorGenerator  :IIncrementalGenerator
{
    private const string NamedEventTriggerBehaviorAttributeSource = """
// <auto-generated/>

using System;

namespace Cirrus.Generated.Attributes;

/// <summary>
/// Attribute to generate a class that inherits from <see cref="Cirrus.Behaviors.Generated.EventTriggerBehaviorBase{T}"/>
/// boun to the event whose name is specified by <paramref name="eventName" />.
/// </summary>
/// <param name="eventName">Name of the triggered event.</param>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
internal class NamedEventTriggerBehaviorAttribute(Type baseType, string eventName) : Attribute
{
    /// <summary>
    /// Base type of the object associated with the generated behavior.
    /// </summary>
    public Type BaseType { get; } = baseType;
    
    /// <summary>
    /// Named of the triggered event.
    /// </summary>
    public string EventName { get; } = eventName;
    
    /// <summary>
    /// Optional list of assembly names to limit the search scope of duck property getters.
    /// If this is not set, all assemblies will be searched.
    /// </summary>
    public string[] Assemblies { get; init; } = [];
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("NamedEventTriggerBehaviorAttribute.g.cs", SourceText.From(NamedEventTriggerBehaviorAttributeSource, Encoding.UTF8));
        });

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (ctx, _) =>
                {
                    var classSyntax = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol symbol) return null;

                    var targetAttributes = symbol.GetAttributes()
                        .Where(a => a.AttributeClass?.Name == "NamedEventTriggerBehaviorAttribute")
                        .ToList();

                    if (targetAttributes.Count == 0) return null;

                    return new { Symbol = symbol, Attributes = targetAttributes };
                }
            ).Where(static m => m is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var compilation = source.Left;
            var classes = source.Right;

            if (classes.IsDefaultOrEmpty) return;

            HashSet<string> generatedClasses = new();

            foreach (var classData in classes)
            {
                if (classData is null) continue;
                var namespaceName = classData.Symbol.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : classData.Symbol.ContainingNamespace.ToDisplayString();

                foreach (var attr in classData.Attributes)
                {
                    if (attr.ConstructorArguments.Length < 2) continue;

                    var baseTypeSymbol = attr.ConstructorArguments[0].Value as ITypeSymbol;
                    var eventName = attr.ConstructorArguments[1].Value as string;

                    if (baseTypeSymbol == null || string.IsNullOrEmpty(eventName)) continue;

                    var className = $"{eventName}EventTriggerBehavior";
                    if (!generatedClasses.Add(className)) continue;

                    var assemblies = GatherAssemblies(attr);
                    var matchedTypes = GetMatchedTypes(compilation, baseTypeSymbol, eventName!, assemblies);

                    GenerateBehaviorClass(spc, namespaceName, className, baseTypeSymbol, eventName!, matchedTypes);
                }
            }
        });
    }
    
    private static void GenerateBehaviorClass(
        SourceProductionContext spc, 
        string? namespaceName, 
        string className, 
        ITypeSymbol baseTypeSymbol, 
        string eventName, 
        List<INamedTypeSymbol> matchedTypes)
    {
        var baseTypeName = baseTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();

        if (namespaceName != null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        sb.AppendLine($"internal class {className} : Cirrus.Behaviors.Primitives.EventTriggerBehaviorBase<{baseTypeName}>");
        sb.AppendLine("{");

        sb.AppendLine($"    protected override bool RegisterEventCore({baseTypeName} source)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (source)");
        sb.AppendLine("        {");
        sb.AppendLine("            case null: return false;");

        foreach (var type in matchedTypes)
        {
            var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            case {typeName} s:");
            sb.AppendLine($"                s.{eventName} -= OnEvent;");
            sb.AppendLine($"                s.{eventName} += OnEvent;");
            sb.AppendLine("                return true;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new NotSupportedException($\"Unsupported source type: {source.GetType().FullName}.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    protected override void UnregisterEventCore({baseTypeName} source)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (source)");
        sb.AppendLine("        {");
        sb.AppendLine("            case null: return;");

        foreach (var type in matchedTypes)
        {
            var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            case {typeName} s:");
            sb.AppendLine($"                s.{eventName} -= OnEvent;");
            sb.AppendLine("                return;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new NotSupportedException($\"Unsupported source type: {source.GetType().FullName}.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        spc.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static HashSet<string> GatherAssemblies(AttributeData attr)
    {
        HashSet<string> assemblies = new();
        var assembliesArgs = attr.NamedArguments.FirstOrDefault(kv => kv.Key == "Assemblies").Value;
        if (assembliesArgs.IsNull) return assemblies;
        foreach (var v in assembliesArgs.Values)
        {
            if (v.Value is string s) assemblies.Add(s);
        }
        return assemblies;
    }

    private static List<INamedTypeSymbol> GetMatchedTypes(
        Compilation compilation,
        ITypeSymbol baseTypeSymbol,
        string eventName,
        HashSet<string> assemblies)
    {
        List<INamedTypeSymbol> matchedTypes = [];
        HashSet<IAssemblySymbol> assembliesToScan = new(SymbolEqualityComparer.Default)
        {
            compilation.Assembly
        };
        
        bool hasExplicitScope = assemblies.Count > 0;
        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol asmSymbol)
            {
                if (hasExplicitScope)
                {
                    if (assemblies.Contains(asmSymbol.Name)) assembliesToScan.Add(asmSymbol);
                }
                else
                {
                    assembliesToScan.Add(asmSymbol);
                }
            }
        }

        void ScanNamespace(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                if (type.IsAbstract || !InheritsFrom(type, baseTypeSymbol)) continue;
                if (type.GetMembers(eventName).OfType<IEventSymbol>().Any())
                {
                    matchedTypes.Add(type);
                }
            }

            foreach (var childNs in ns.GetNamespaceMembers())
            {
                ScanNamespace(childNs);
            }
        }

        foreach (var asm in assembliesToScan)
        {
            ScanNamespace(asm.GlobalNamespace);
        }

        return matchedTypes;
    }

    private static bool InheritsFrom(ITypeSymbol type, ITypeSymbol baseType)
    {
        if (baseType.SpecialType == SpecialType.System_Object) return true;
        if (SymbolEqualityComparer.Default.Equals(type, baseType)) return true;
        
        var currentBaseType = type.BaseType;
        while (currentBaseType != null)
        {
            if (SymbolEqualityComparer.Default.Equals(currentBaseType, baseType)) return true;
            currentBaseType = currentBaseType.BaseType;
        }
        
        if (baseType.TypeKind == TypeKind.Interface)
        {
            return type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, baseType));
        }
        
        return false;
    }
}